name: Update Docker Hub description

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/update-dockerhub-description.yml'

env:
  IMAGE_NAME: nginx-webdav-nononsense
  
jobs:
  update:
    name: Update Docker Hub description
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: update docker hub repository description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
